//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29
//  @ Author : chenxiaoyu
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueForKey( const std::string &key) {

	return _dictionary->valueForKey(key)->intValue();
}

const char* StaticData::stringValueFromKey(const std::string &key) {

	return _dictionary->valueForKey(key)->getCString();
}

float StaticData::floatValueFromKey(const std::string &key) {

	return _dictionary->valueForKey(key)->floatValue();
}

bool StaticData::booleanFromKey(const std::string &key) {

	return _dictionary->valueForKey(key)->boolValue();
}

coco2d::CCPoint StaticData::pointFromKey(const std::string &key) {

	return CCPointFromString(_dictionary->valueForKey(key)->getCString());
}

coco2d::CCRect StaticData::rectFromKey(const std::string &key) {

	return CCRectFromString(_dictionary->valueForKey(key)->getCString());
}

coco2d::CCSize StaticData::sizeFromKey(const std::string &key) {
	
	return CCSizeFromString(_dictionary->valueForKey(key)->getCString());
}

bool StaticData::init() {

	_dictionary=CCDictionary::createWithContentsOfFile(_staticFileName.c_str());
	_dictionary->retain();
	return true;
}

StaticData::StaticData() {

}

StaticData::~StaticData() {

}

