//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.h
//  @ Date : 2017/9/29
//  @ Author : chenxiaoyu
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	static StaticData sharedStaticData();
	static void purge();
	int intValueForKey( const std::string &key);
	const char* stringValueFromKey(const std::string &key);
	float floatValueFromKey(const std::string &key);
	bool booleanFromKey(const std::string &key);
	coco2d::CCPoint pointFromKey(const std::string &key);
	coco2d::CCRect rectFromKey(const std::string &key);
	coco2d::CCSize sizeFromKey(const std::string &key);
protected:
	coco2d::CCDictionary _dictionary;
	std::string _staticFileName;
	bool init();
private:
	StaticData();
	~StaticData();
};

#endif  //_STATICDATA_H
